language: node_js
node_js:
  - "10"
services:
  - postgresql
before_script:
  - psql -c 'create database budget_tracker_test;' -U postgres
  - psql budget_tracker_test -c 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp";'
  - npm install -g mocha
  - npm install -g codeclimate-test-reporter
after_success:
  - codeclimate < ./coverage/lcov.info